// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_cBq_scQFprIzs1cjYwq-3fji252D0k',
    appId: '1:257992393532:web:d83f72e033d9ef59065439',
    messagingSenderId: '257992393532',
    projectId: 'goatkart',
    authDomain: 'goatkart.firebaseapp.com',
    storageBucket: 'goatkart.firebasestorage.app',
    measurementId: 'G-7LF0RDVR0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAguqFk2PuyyPmaC1S6GsSvj9HH2Fjgr_8',
    appId: '1:257992393532:android:fc68a026d157e3e2065439',
    messagingSenderId: '257992393532',
    projectId: 'goatkart',
    storageBucket: 'goatkart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PG05sZAjRw2_LKs9wMm4wNN1Q-6wHEU',
    appId: '1:257992393532:ios:7919c3348091fa6f065439',
    messagingSenderId: '257992393532',
    projectId: 'goatkart',
    storageBucket: 'goatkart.firebasestorage.app',
    iosBundleId: 'com.example.goatkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-PG05sZAjRw2_LKs9wMm4wNN1Q-6wHEU',
    appId: '1:257992393532:ios:7919c3348091fa6f065439',
    messagingSenderId: '257992393532',
    projectId: 'goatkart',
    storageBucket: 'goatkart.firebasestorage.app',
    iosBundleId: 'com.example.goatkart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_cBq_scQFprIzs1cjYwq-3fji252D0k',
    appId: '1:257992393532:web:de074e12605483b5065439',
    messagingSenderId: '257992393532',
    projectId: 'goatkart',
    authDomain: 'goatkart.firebaseapp.com',
    storageBucket: 'goatkart.firebasestorage.app',
    measurementId: 'G-5SE38QEH5X',
  );
}
